const Utils = require('../lib/utils')

const Miner = require('../lib/miner/miner')
const rlp = require('rlp')

const utils = new Utils()
const key = utils.generatorKeyPair('this is secret!')
const Account = require('../lib/account/account')
const c = utils.generatorSignature('Moechain is comming', key.secretKey)
console.log('signature:' + c)
console.log(utils.verifySignature('moechsiniscomming', c, key.publicKey))
console.log(utils.verifySignature('Moechain is comming', c, key.publicKey))
console.log(utils.generatorAddress(key.publicKey))

let a = utils.generatorBlockHash({a: 233333, b: 33333332})
console.log(a)
let account = new Account(['23','384'])
console.log(rlp.decode(account.serialize()).toString())
let miner = new Miner()
miner.mine(1, 13107)
